version: '3'

services:
  worker1:
    image: "worker:latest"
    env_file: network.env
    environment:  
    - MODEL=${MODEL}
    - KEY=${KEY1}
    - DECFL_ID=0
    - DECFL_PARTITIONS=3
  worker2:
    image: "worker:latest"
    env_file: network.env
    environment:  
    - MODEL=${MODEL}
    - KEY=${KEY2}
    - DECFL_ID=1
    - DECFL_PARTITIONS=3
  worker3:
    image: "worker:latest"
    env_file: network.env
    environment:  
      - MODEL=${MODEL}
      - KEY=${KEY3}
      - DECFL_ID=2
      - DECFL_PARTITIONS=3

networks:
  default:
    external:
      name: myNet