- hosts: all
  tasks:
    - name: Create app directory
      file:
        path: ~/app
        state: directory
        mode: '0755'
    - name: Copy worker executable
      copy: 
        src: ../app/worker/worker
        dest: ~/app/worker
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ../app/worker/Dockerfile
        dest: ~/app/Dockerfile
    - name: build docker image
      docker_image:
        name: decfl-worker
        path: /home/ubuntu/app
        state: present
        force: yes
      become: yes