- hosts: all
  vars:
    model: "{{ MODEL }}"
    chain: "{{ CHAIN }}"
  tasks:
    - name: Run Training
      docker_container:
        name: worker_{{ model | regex_search('.{6}') }}
        image: decfl-worker:latest
        state: started
        env:
            MODEL: "{{ model }}"
            STORAGE: ipfs:5001
            STORAGE_TYPE: ipfs
            CHAIN: "{{ chain }}"
        env_file: /home/ubuntu/app/identity
        networks:
          - name: decfl_net
      become: yes