- hosts: all
  tasks:
    - name: Setup network
      docker_network:
        name: decfl_net
        state: present
      become: yes
    - name: Volume for IPFS
      docker_volume:
        name: ipfs-data
      become: yes
    - name: Setup IPFS
      docker_container:
        name: ipfs
        image: ipfs/go-ipfs:latest
        state: started
#        container_default_behavior: compatibility
        volumes:
          - ipfs-data:/data/ipfs
        ports:
          - "4001:4001"
          - "127.0.0.1:5001:5001"
          - "127.0.0.1:8080:8080"
        networks:
          - name: decfl_net
        networks_cli_compatible: yes
        network_mode: default
      become: yes
